
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend